version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    # Внутренний порт контейнера — 3000
    ports:
      - "3000"           # не указываем внешний порт
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: 3000
    restart: unless-stopped
